# --- 第一阶段：Builder (编译环境) ---
FROM golang:1.25-alpine AS builder

# 1. 设置工作目录

ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o gateway_server ./cmd/api_gateway/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/gateway_server .

EXPOSE 8080

CMD ["./gateway_server", "-config", "/app/config/config.yaml"]
