FROM golang:1.25-alpine AS builder

ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o relay_server ./cmd/relay/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app

COPY --from=builder /app/relay_server .

CMD ["./relay_server", "-config", "/app/config/config.yaml"]

