// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: types/doc.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Keyword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"` // 字段名, 如"title"
	Word          string                 `protobuf:"bytes,2,opt,name=Word,proto3" json:"Word,omitempty"`   //关键词内容, 如"go"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyword) Reset() {
	*x = Keyword{}
	mi := &file_types_doc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyword) ProtoMessage() {}

func (x *Keyword) ProtoReflect() protoreflect.Message {
	mi := &file_types_doc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyword.ProtoReflect.Descriptor instead.
func (*Keyword) Descriptor() ([]byte, []int) {
	return file_types_doc_proto_rawDescGZIP(), []int{0}
}

func (x *Keyword) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Keyword) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                    //业务侧唯一ID(如视频ID)
	IntId         uint64                 `protobuf:"varint,2,opt,name=IntId,proto3" json:"IntId,omitempty"`             //内部自增ID(用于优化存储)
	BitsFeature   uint64                 `protobuf:"varint,3,opt,name=BitsFeature,proto3" json:"BitsFeature,omitempty"` //位图特征(用于快速过滤)
	Keyword       []*Keyword             `protobuf:"bytes,4,rep,name=Keyword,proto3" json:"Keyword,omitempty"`          //包含的关键词列表
	Bytes         []byte                 `protobuf:"bytes,5,opt,name=Bytes,proto3" json:"Bytes,omitempty"`              //原始数据的二进制内容
	Score         float64                `protobuf:"fixed64,6,opt,name=Score,proto3" json:"Score,omitempty"`            //搜索打分
	Content       string                 `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`          //待分词的正文内容
	Title         string                 `protobuf:"bytes,8,opt,name=Title,proto3" json:"Title,omitempty"`
	Url           string                 `protobuf:"bytes,9,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_types_doc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_types_doc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_types_doc_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetIntId() uint64 {
	if x != nil {
		return x.IntId
	}
	return 0
}

func (x *Document) GetBitsFeature() uint64 {
	if x != nil {
		return x.BitsFeature
	}
	return 0
}

func (x *Document) GetKeyword() []*Keyword {
	if x != nil {
		return x.Keyword
	}
	return nil
}

func (x *Document) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Document) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_types_doc_proto protoreflect.FileDescriptor

const file_types_doc_proto_rawDesc = "" +
	"\n" +
	"\x0ftypes/doc.proto\x12\x05types\"3\n" +
	"\aKeyword\x12\x14\n" +
	"\x05Field\x18\x01 \x01(\tR\x05Field\x12\x12\n" +
	"\x04Word\x18\x02 \x01(\tR\x04Word\"\xea\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x14\n" +
	"\x05IntId\x18\x02 \x01(\x04R\x05IntId\x12 \n" +
	"\vBitsFeature\x18\x03 \x01(\x04R\vBitsFeature\x12(\n" +
	"\aKeyword\x18\x04 \x03(\v2\x0e.types.KeywordR\aKeyword\x12\x14\n" +
	"\x05Bytes\x18\x05 \x01(\fR\x05Bytes\x12\x14\n" +
	"\x05Score\x18\x06 \x01(\x01R\x05Score\x12\x18\n" +
	"\aContent\x18\a \x01(\tR\aContent\x12\x14\n" +
	"\x05Title\x18\b \x01(\tR\x05Title\x12\x10\n" +
	"\x03Url\x18\t \x01(\tR\x03UrlB\x10Z\x0emy_radic/typesb\x06proto3"

var (
	file_types_doc_proto_rawDescOnce sync.Once
	file_types_doc_proto_rawDescData []byte
)

func file_types_doc_proto_rawDescGZIP() []byte {
	file_types_doc_proto_rawDescOnce.Do(func() {
		file_types_doc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_doc_proto_rawDesc), len(file_types_doc_proto_rawDesc)))
	})
	return file_types_doc_proto_rawDescData
}

var file_types_doc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_doc_proto_goTypes = []any{
	(*Keyword)(nil),  // 0: types.Keyword
	(*Document)(nil), // 1: types.Document
}
var file_types_doc_proto_depIdxs = []int32{
	0, // 0: types.Document.Keyword:type_name -> types.Keyword
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_doc_proto_init() }
func file_types_doc_proto_init() {
	if File_types_doc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_doc_proto_rawDesc), len(file_types_doc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_doc_proto_goTypes,
		DependencyIndexes: file_types_doc_proto_depIdxs,
		MessageInfos:      file_types_doc_proto_msgTypes,
	}.Build()
	File_types_doc_proto = out.File
	file_types_doc_proto_goTypes = nil
	file_types_doc_proto_depIdxs = nil
}
