// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: types/term_query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TermQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       *Keyword               `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Must          []*TermQuery           `protobuf:"bytes,2,rep,name=must,proto3" json:"must,omitempty"`
	Should        []*TermQuery           `protobuf:"bytes,3,rep,name=should,proto3" json:"should,omitempty"`
	OnFlag        uint64                 `protobuf:"varint,4,opt,name=on_flag,json=onFlag,proto3" json:"on_flag,omitempty"`
	OffFlag       uint64                 `protobuf:"varint,5,opt,name=off_flag,json=offFlag,proto3" json:"off_flag,omitempty"`
	OrFlag        []uint64               `protobuf:"varint,6,rep,packed,name=or_flag,json=orFlag,proto3" json:"or_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermQuery) Reset() {
	*x = TermQuery{}
	mi := &file_types_term_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermQuery) ProtoMessage() {}

func (x *TermQuery) ProtoReflect() protoreflect.Message {
	mi := &file_types_term_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermQuery.ProtoReflect.Descriptor instead.
func (*TermQuery) Descriptor() ([]byte, []int) {
	return file_types_term_query_proto_rawDescGZIP(), []int{0}
}

func (x *TermQuery) GetKeyword() *Keyword {
	if x != nil {
		return x.Keyword
	}
	return nil
}

func (x *TermQuery) GetMust() []*TermQuery {
	if x != nil {
		return x.Must
	}
	return nil
}

func (x *TermQuery) GetShould() []*TermQuery {
	if x != nil {
		return x.Should
	}
	return nil
}

func (x *TermQuery) GetOnFlag() uint64 {
	if x != nil {
		return x.OnFlag
	}
	return 0
}

func (x *TermQuery) GetOffFlag() uint64 {
	if x != nil {
		return x.OffFlag
	}
	return 0
}

func (x *TermQuery) GetOrFlag() []uint64 {
	if x != nil {
		return x.OrFlag
	}
	return nil
}

var File_types_term_query_proto protoreflect.FileDescriptor

const file_types_term_query_proto_rawDesc = "" +
	"\n" +
	"\x16types/term_query.proto\x12\x05types\x1a\x0ftypes/doc.proto\"\xd2\x01\n" +
	"\tTermQuery\x12(\n" +
	"\akeyword\x18\x01 \x01(\v2\x0e.types.KeywordR\akeyword\x12$\n" +
	"\x04must\x18\x02 \x03(\v2\x10.types.TermQueryR\x04must\x12(\n" +
	"\x06should\x18\x03 \x03(\v2\x10.types.TermQueryR\x06should\x12\x17\n" +
	"\aon_flag\x18\x04 \x01(\x04R\x06onFlag\x12\x19\n" +
	"\boff_flag\x18\x05 \x01(\x04R\aoffFlag\x12\x17\n" +
	"\aor_flag\x18\x06 \x03(\x04R\x06orFlagB\x10Z\x0emy_radic/typesb\x06proto3"

var (
	file_types_term_query_proto_rawDescOnce sync.Once
	file_types_term_query_proto_rawDescData []byte
)

func file_types_term_query_proto_rawDescGZIP() []byte {
	file_types_term_query_proto_rawDescOnce.Do(func() {
		file_types_term_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_term_query_proto_rawDesc), len(file_types_term_query_proto_rawDesc)))
	})
	return file_types_term_query_proto_rawDescData
}

var file_types_term_query_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_term_query_proto_goTypes = []any{
	(*TermQuery)(nil), // 0: types.TermQuery
	(*Keyword)(nil),   // 1: types.Keyword
}
var file_types_term_query_proto_depIdxs = []int32{
	1, // 0: types.TermQuery.keyword:type_name -> types.Keyword
	0, // 1: types.TermQuery.must:type_name -> types.TermQuery
	0, // 2: types.TermQuery.should:type_name -> types.TermQuery
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_types_term_query_proto_init() }
func file_types_term_query_proto_init() {
	if File_types_term_query_proto != nil {
		return
	}
	file_types_doc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_term_query_proto_rawDesc), len(file_types_term_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_term_query_proto_goTypes,
		DependencyIndexes: file_types_term_query_proto_depIdxs,
		MessageInfos:      file_types_term_query_proto_msgTypes,
	}.Build()
	File_types_term_query_proto = out.File
	file_types_term_query_proto_goTypes = nil
	file_types_term_query_proto_depIdxs = nil
}
