// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: index_service/index_service.proto

package index_service

import (
	types "my_radic/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddDocRequest: 添加文档请求
type AddDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           *types.Document        `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocRequest) Reset() {
	*x = AddDocRequest{}
	mi := &file_index_service_index_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocRequest) ProtoMessage() {}

func (x *AddDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocRequest.ProtoReflect.Descriptor instead.
func (*AddDocRequest) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddDocRequest) GetDoc() *types.Document {
	if x != nil {
		return x.Doc
	}
	return nil
}

// AddDocResponse: 添加文档响应
type AddDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint64                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocResponse) Reset() {
	*x = AddDocResponse{}
	mi := &file_index_service_index_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocResponse) ProtoMessage() {}

func (x *AddDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocResponse.ProtoReflect.Descriptor instead.
func (*AddDocResponse) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddDocResponse) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *AddDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeleteDocRequest: 删除文档请求
type DeleteDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint64                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"` // 内部 ID (IntId)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocRequest) Reset() {
	*x = DeleteDocRequest{}
	mi := &file_index_service_index_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocRequest) ProtoMessage() {}

func (x *DeleteDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocRequest) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDocRequest) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

// DeleteDocResponse: 删除结果响应
type DeleteDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocResponse) Reset() {
	*x = DeleteDocResponse{}
	mi := &file_index_service_index_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocResponse) ProtoMessage() {}

func (x *DeleteDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocResponse) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDocResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SearchRequest: 搜索请求
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *types.TermQuery       `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_index_service_index_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetQuery() *types.TermQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// SearchResponse: 搜索结果
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*types.Document      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_index_service_index_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetResults() []*types.Document {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 批量添加文档
type BatchAddDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          []*types.Document      `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAddDocRequest) Reset() {
	*x = BatchAddDocRequest{}
	mi := &file_index_service_index_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAddDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAddDocRequest) ProtoMessage() {}

func (x *BatchAddDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAddDocRequest.ProtoReflect.Descriptor instead.
func (*BatchAddDocRequest) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{6}
}

func (x *BatchAddDocRequest) GetDocs() []*types.Document {
	if x != nil {
		return x.Docs
	}
	return nil
}

// 批量添加文档响应
type BatchAddDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocIds        []uint64               `protobuf:"varint,1,rep,packed,name=doc_ids,json=docIds,proto3" json:"doc_ids,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAddDocResponse) Reset() {
	*x = BatchAddDocResponse{}
	mi := &file_index_service_index_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAddDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAddDocResponse) ProtoMessage() {}

func (x *BatchAddDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAddDocResponse.ProtoReflect.Descriptor instead.
func (*BatchAddDocResponse) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{7}
}

func (x *BatchAddDocResponse) GetDocIds() []uint64 {
	if x != nil {
		return x.DocIds
	}
	return nil
}

func (x *BatchAddDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 批量删除文档
type BatchDeleteDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocIds        []uint64               `protobuf:"varint,1,rep,packed,name=doc_ids,json=docIds,proto3" json:"doc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteDocRequest) Reset() {
	*x = BatchDeleteDocRequest{}
	mi := &file_index_service_index_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteDocRequest) ProtoMessage() {}

func (x *BatchDeleteDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteDocRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteDocRequest) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{8}
}

func (x *BatchDeleteDocRequest) GetDocIds() []uint64 {
	if x != nil {
		return x.DocIds
	}
	return nil
}

// 批量删除文档响应
type BatchDeleteDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteDocResponse) Reset() {
	*x = BatchDeleteDocResponse{}
	mi := &file_index_service_index_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteDocResponse) ProtoMessage() {}

func (x *BatchDeleteDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteDocResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteDocResponse) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDeleteDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchDeleteDocResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ServiceNodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceAddr   string                 `protobuf:"bytes,1,opt,name=service_addr,json=serviceAddr,proto3" json:"service_addr,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	ShardId       int32                  `protobuf:"varint,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TotalShards   int32                  `protobuf:"varint,4,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceNodeInfo) Reset() {
	*x = ServiceNodeInfo{}
	mi := &file_index_service_index_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNodeInfo) ProtoMessage() {}

func (x *ServiceNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_index_service_index_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNodeInfo.ProtoReflect.Descriptor instead.
func (*ServiceNodeInfo) Descriptor() ([]byte, []int) {
	return file_index_service_index_service_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceNodeInfo) GetServiceAddr() string {
	if x != nil {
		return x.ServiceAddr
	}
	return ""
}

func (x *ServiceNodeInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ServiceNodeInfo) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ServiceNodeInfo) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

var File_index_service_index_service_proto protoreflect.FileDescriptor

const file_index_service_index_service_proto_rawDesc = "" +
	"\n" +
	"!index_service/index_service.proto\x12\rindex_service\x1a\x0ftypes/doc.proto\x1a\x16types/term_query.proto\"2\n" +
	"\rAddDocRequest\x12!\n" +
	"\x03doc\x18\x01 \x01(\v2\x0f.types.DocumentR\x03doc\"A\n" +
	"\x0eAddDocResponse\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\")\n" +
	"\x10DeleteDocRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\"C\n" +
	"\x11DeleteDocResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"7\n" +
	"\rSearchRequest\x12&\n" +
	"\x05query\x18\x01 \x01(\v2\x10.types.TermQueryR\x05query\"Q\n" +
	"\x0eSearchResponse\x12)\n" +
	"\aresults\x18\x01 \x03(\v2\x0f.types.DocumentR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"9\n" +
	"\x12BatchAddDocRequest\x12#\n" +
	"\x04docs\x18\x01 \x03(\v2\x0f.types.DocumentR\x04docs\"H\n" +
	"\x13BatchAddDocResponse\x12\x17\n" +
	"\adoc_ids\x18\x01 \x03(\x04R\x06docIds\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"0\n" +
	"\x15BatchDeleteDocRequest\x12\x17\n" +
	"\adoc_ids\x18\x01 \x03(\x04R\x06docIds\"H\n" +
	"\x16BatchDeleteDocResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8a\x01\n" +
	"\x0fServiceNodeInfo\x12!\n" +
	"\fservice_addr\x18\x01 \x01(\tR\vserviceAddr\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\x05R\ashardId\x12!\n" +
	"\ftotal_shards\x18\x04 \x01(\x05R\vtotalShards2\xa1\x03\n" +
	"\fIndexService\x12E\n" +
	"\x06AddDoc\x12\x1c.index_service.AddDocRequest\x1a\x1d.index_service.AddDocResponse\x12N\n" +
	"\tDeleteDoc\x12\x1f.index_service.DeleteDocRequest\x1a .index_service.DeleteDocResponse\x12T\n" +
	"\vBatchAddDoc\x12!.index_service.BatchAddDocRequest\x1a\".index_service.BatchAddDocResponse\x12]\n" +
	"\x0eBatchDeleteDoc\x12$.index_service.BatchDeleteDocRequest\x1a%.index_service.BatchDeleteDocResponse\x12E\n" +
	"\x06Search\x12\x1c.index_service.SearchRequest\x1a\x1d.index_service.SearchResponseB\x18Z\x16my_radic/index_serviceb\x06proto3"

var (
	file_index_service_index_service_proto_rawDescOnce sync.Once
	file_index_service_index_service_proto_rawDescData []byte
)

func file_index_service_index_service_proto_rawDescGZIP() []byte {
	file_index_service_index_service_proto_rawDescOnce.Do(func() {
		file_index_service_index_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_index_service_index_service_proto_rawDesc), len(file_index_service_index_service_proto_rawDesc)))
	})
	return file_index_service_index_service_proto_rawDescData
}

var file_index_service_index_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_index_service_index_service_proto_goTypes = []any{
	(*AddDocRequest)(nil),          // 0: index_service.AddDocRequest
	(*AddDocResponse)(nil),         // 1: index_service.AddDocResponse
	(*DeleteDocRequest)(nil),       // 2: index_service.DeleteDocRequest
	(*DeleteDocResponse)(nil),      // 3: index_service.DeleteDocResponse
	(*SearchRequest)(nil),          // 4: index_service.SearchRequest
	(*SearchResponse)(nil),         // 5: index_service.SearchResponse
	(*BatchAddDocRequest)(nil),     // 6: index_service.BatchAddDocRequest
	(*BatchAddDocResponse)(nil),    // 7: index_service.BatchAddDocResponse
	(*BatchDeleteDocRequest)(nil),  // 8: index_service.BatchDeleteDocRequest
	(*BatchDeleteDocResponse)(nil), // 9: index_service.BatchDeleteDocResponse
	(*ServiceNodeInfo)(nil),        // 10: index_service.ServiceNodeInfo
	(*types.Document)(nil),         // 11: types.Document
	(*types.TermQuery)(nil),        // 12: types.TermQuery
}
var file_index_service_index_service_proto_depIdxs = []int32{
	11, // 0: index_service.AddDocRequest.doc:type_name -> types.Document
	12, // 1: index_service.SearchRequest.query:type_name -> types.TermQuery
	11, // 2: index_service.SearchResponse.results:type_name -> types.Document
	11, // 3: index_service.BatchAddDocRequest.docs:type_name -> types.Document
	0,  // 4: index_service.IndexService.AddDoc:input_type -> index_service.AddDocRequest
	2,  // 5: index_service.IndexService.DeleteDoc:input_type -> index_service.DeleteDocRequest
	6,  // 6: index_service.IndexService.BatchAddDoc:input_type -> index_service.BatchAddDocRequest
	8,  // 7: index_service.IndexService.BatchDeleteDoc:input_type -> index_service.BatchDeleteDocRequest
	4,  // 8: index_service.IndexService.Search:input_type -> index_service.SearchRequest
	1,  // 9: index_service.IndexService.AddDoc:output_type -> index_service.AddDocResponse
	3,  // 10: index_service.IndexService.DeleteDoc:output_type -> index_service.DeleteDocResponse
	7,  // 11: index_service.IndexService.BatchAddDoc:output_type -> index_service.BatchAddDocResponse
	9,  // 12: index_service.IndexService.BatchDeleteDoc:output_type -> index_service.BatchDeleteDocResponse
	5,  // 13: index_service.IndexService.Search:output_type -> index_service.SearchResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_index_service_index_service_proto_init() }
func file_index_service_index_service_proto_init() {
	if File_index_service_index_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_index_service_index_service_proto_rawDesc), len(file_index_service_index_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_index_service_index_service_proto_goTypes,
		DependencyIndexes: file_index_service_index_service_proto_depIdxs,
		MessageInfos:      file_index_service_index_service_proto_msgTypes,
	}.Build()
	File_index_service_index_service_proto = out.File
	file_index_service_index_service_proto_goTypes = nil
	file_index_service_index_service_proto_depIdxs = nil
}
